In [1]:
from scipy.optimize import minimize
from scipy.stats import norm
import numpy as np
import statsmodels.api as sm
import pandas as pd
from classes import GLM_Normal, GLM_Bernoulli, GLM_Poisson

In [57]:
#data sets
warpbreaks = pd.read_csv("warpbreaks.csv") #for Poisson distribution
duncan = sm.datasets.get_rdataset("Duncan", "carData") #for Normal Distribution
duncan = pd.DataFrame(data = duncan.data) #easier to use
spector = sm.datasets.spector.load_pandas() #for Bernoulli distribution
print("warpbreaks: ","\n", warpbreaks.head())
print("duncan: ","\n", duncan.head())
print("spector: ","\n", spector.data.head())


warpbreaks:  
    breaks  wool  tension
0      26     0        0
1      30     0        0
2      54     0        0
3      25     0        0
4      70     0        0
duncan:  
             type  income  education  prestige
rownames                                     
accountant  prof      62         86        82
pilot       prof      72         76        83
architect   prof      75         92        90
author      prof      55         90        76
chemist     prof      64         86        90
spector:  
     GPA  TUCE  PSI  GRADE
0  2.66  20.0  0.0    0.0
1  2.89  22.0  0.0    0.0
2  3.28  24.0  0.0    0.0
3  2.92  12.0  0.0    0.0
4  4.00  21.0  0.0    1.0


Allocating data for Normal Distribution

In [58]:
y_normal = duncan['income']
X_normal = sm.add_constant(duncan[['education', 'prestige']])

Allocating data for Bernoulli distribution

In [59]:
y_Bernoulli = spector.endog
X_Bernoulli = sm.add_constant(spector.exog)

Allocating data for Poisson distribution

In [60]:
y_Poisson = warpbreaks['breaks']
X_Poisson = sm.add_constant(warpbreaks[['wool', 'tension']])

Fittig models using sm.GLM

In [ ]:
normal_mod = sm.GLM(y_normal, X_normal, family = sm.families.Gaussian()).fit() #normal
logit_mod = sm.GLM(y_Bernoulli, X_Bernoulli, family = sm.families.Binomial()).fit() #bernoulli
poisson_mod = sm.GLM(y_Poisson, X_Poisson, family = sm.families.Poisson()).fit() #poisson

Fitting models using my classes and comparing results

In [ ]:
normal_glm = GLM_Normal(X_normal, y_normal)
normal_glm.fit()
normal_glm.prediction(X_normal)

[10.42635945  0.03226317  0.62372386]


array([64.34634812, 64.64744032, 69.52971799, 60.73305764, 69.33613899,
       67.40044108, 71.43315273, 69.78782332, 45.66689555, 68.08869127,
       48.36609368, 69.09957313, 74.05710083, 49.93617306, 58.89414923,
       35.22481371, 59.28121515, 62.75472927, 39.91351239, 70.45453404,
       37.0745379 , 33.40744478, 38.28972245, 22.0190995 , 31.75129959,
       44.74198742, 53.1192266 , 47.01104068, 27.35296942, 29.32093049,
       17.59922986, 20.00805949, 23.11595508, 17.27659819, 19.0187171 ,
       26.04099537, 23.73967894, 15.69579512, 12.84600485, 21.11573084,
       15.13659759, 18.09390105, 16.06141364, 37.51540645, 17.69601936])

In [74]:
print(normal_mod.params.values)
print(normal_mod.predict(X_normal))

[10.42636103  0.03226315  0.62372386]
rownames
accountant            64.346348
pilot                 64.647441
architect             69.529718
author                60.733058
chemist               69.336139
minister              67.400441
professor             71.433153
dentist               69.787823
reporter              45.666896
engineer              68.088692
undertaker            48.366094
lawyer                69.099573
physician             74.057101
welfare.worker        49.936173
teacher               58.894149
conductor             35.224815
contractor            59.281216
factory.owner         62.754730
store.manager         39.913513
banker                70.454534
bookkeeper            37.074538
mail.carrier          33.407446
insurance.agent       38.289723
store.clerk           22.019100
carpenter             31.751301
electrician           44.741988
RR.engineer           53.119228
machinist             47.011042
auto.repairman        27.352971
plumber               29.

In [75]:
bernoulli_glm = GLM_Bernoulli(X_Bernoulli, y_Bernoulli)
bernoulli_glm.fit()
bernoulli_glm.prediction(X_Bernoulli)

[-13.02133824   2.82611282   0.09515727   2.37868716]


array([0.02657803, 0.05950129, 0.18725991, 0.02590175, 0.56989325,
       0.03485835, 0.02650412, 0.05155905, 0.1111266 , 0.6935109 ,
       0.0244704 , 0.18999748, 0.32223963, 0.19321108, 0.36098972,
       0.0301838 , 0.05362638, 0.0385884 , 0.58987243, 0.6607856 ,
       0.06137584, 0.90484709, 0.24177305, 0.85209072, 0.83829043,
       0.48113256, 0.63542109, 0.3072185 , 0.84170421, 0.94534025,
       0.52911733, 0.11103096])

In [76]:
print(logit_mod.params.values)
print(logit_mod.predict(X_Bernoulli))

[-13.02134686   2.82611259   0.09515766   2.37868765]
0     0.026578
1     0.059501
2     0.187260
3     0.025902
4     0.569893
5     0.034858
6     0.026504
7     0.051559
8     0.111127
9     0.693511
10    0.024470
11    0.189997
12    0.322240
13    0.193211
14    0.360990
15    0.030184
16    0.053626
17    0.038588
18    0.589872
19    0.660786
20    0.061376
21    0.904847
22    0.241772
23    0.852091
24    0.838291
25    0.481133
26    0.635421
27    0.307219
28    0.841704
29    0.945340
30    0.529117
31    0.111031
dtype: float64


In [77]:
poisson_glm = GLM_Poisson(X_Poisson, y_Poisson)
poisson_glm.fit()
poisson_glm.prediction(X_Poisson)

[ 3.67653953 -0.20598844 -0.26455303]


array([39.50943603, 39.50943603, 39.50943603, 39.50943603, 39.50943603,
       39.50943603, 39.50943603, 39.50943603, 39.50943603, 30.32542587,
       30.32542587, 30.32542587, 30.32542587, 30.32542587, 30.32542587,
       30.32542587, 30.32542587, 30.32542587, 23.27624858, 23.27624858,
       23.27624858, 23.27624858, 23.27624858, 23.27624858, 23.27624858,
       23.27624858, 23.27624858, 32.15445766, 32.15445766, 32.15445766,
       32.15445766, 32.15445766, 32.15445766, 32.15445766, 32.15445766,
       32.15445766, 24.68012   , 24.68012   , 24.68012   , 24.68012   ,
       24.68012   , 24.68012   , 24.68012   , 24.68012   , 24.68012   ,
       18.94320002, 18.94320002, 18.94320002, 18.94320002, 18.94320002,
       18.94320002, 18.94320002, 18.94320002, 18.94320002])

In [78]:
print(poisson_mod.params.values)
print(poisson_mod.predict(X_Poisson))

[ 3.67653953 -0.20598844 -0.26455302]
0     39.509436
1     39.509436
2     39.509436
3     39.509436
4     39.509436
5     39.509436
6     39.509436
7     39.509436
8     39.509436
9     30.325426
10    30.325426
11    30.325426
12    30.325426
13    30.325426
14    30.325426
15    30.325426
16    30.325426
17    30.325426
18    23.276249
19    23.276249
20    23.276249
21    23.276249
22    23.276249
23    23.276249
24    23.276249
25    23.276249
26    23.276249
27    32.154458
28    32.154458
29    32.154458
30    32.154458
31    32.154458
32    32.154458
33    32.154458
34    32.154458
35    32.154458
36    24.680120
37    24.680120
38    24.680120
39    24.680120
40    24.680120
41    24.680120
42    24.680120
43    24.680120
44    24.680120
45    18.943200
46    18.943200
47    18.943200
48    18.943200
49    18.943200
50    18.943200
51    18.943200
52    18.943200
53    18.943200
dtype: float64
